data<-read.table("./household_power_consumption.txt", header=TRUE, sep=";", na.strings="?")
data2<-subset(data, Date == "1/2/2007" | Date == "2/2/2007")
data2$DateTime<-as.POSIXct(paste(data2$Date," ",data2$Time), format="%d/%m/%Y %H:%M:%S")
png(filename = "plot2.png", width = 480, height = 480, units = "px")
plot(data2$DateTime, data2$Global_active_power, xlab="", ylab="Global Active Power (kilowatts)", type="l")
dev.off()