data<-read.table("./household_power_consumption.txt", header=TRUE, sep=";", na.strings="?")
data2<-subset(data, Date == "1/2/2007" | Date == "2/2/2007")
data2$DateTime<-as.POSIXct(paste(data2$Date," ",data2$Time), format="%d/%m/%Y %H:%M:%S")

png(filename = "plot3.png", width = 480, height = 480, units = "px")
plot(data2$DateTime, data2$Sub_metering_1, main = "", type = "l", xlab="", ylab="Energy sub metering")
lines(data2$DateTime, data2$Sub_metering_2, col="red")
lines(data2$DateTime, data2$Sub_metering_3, col="blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()